### ISSUE TITLE
[Examples] PyTorch (train and inference), TGI and TEI (inference)

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/Google-Cloud-Containers#40]
As part of our collaboration with Google Cloud and following up #2 to create the Deep Learning Containers (DLCs) for both Google Kubernetes Engine (GKE) and Vertex AI, we want to create dedicated examples per each alternative offered.

The examples to be created and included within this repository are listed below and divided in two categories:

**Edit**: updated as of Philipp's comment below!

- Training
  - Vertex AI
    - [x] Custom Container Training Job to fine-tune (SFT) an LLM via TRL's CLI using QLoRA on a single GPU #44 
    - [x] Custom Container Training Job to full fine-tune (SFT) an LLM via TRL's CLI on N GPUs (N > 1) via `accelerate` #44 
    - [ ] Kubeflow Pipeline to fine-tune an LLM with a custom script on TPU (we already have https://github.com/huggingface/Google-Cloud-Containers/tree/main/examples/tpu-examples/causal-language-modeling)
  - GKE
    - [x] fine-tune (SFT) an LLM via TRL's CLI using QLoRA on a single GPU #53
    - [x] fine-tune (SFT) an LLM via TRL's CLI on N GPUs (N > 1) via accelerate #53

- Inference
  - Vertex AI (already a bunch of existing examples under [`examples/vertex-ai/notebooks`](https://github.com/huggingface/Google-Cloud-Containers/tree/main/examples/vertex-ai/notebooks) only missing review / rewrite) #55 
    - [x] PyTorch via `transformers` using a Custom Prediction Routine (CPR) in Vertex AI with any relevant model for any supported `HF_TASK` other than `text-generation` (could be either CPU, GPU or both)
    - [x] TGI via a pre-built DLC (on GPU) from the Hugging Face Hub
    - [x] TGI via a pre-built DLC (on GPU) from a GCS Bucket
    - [x] TEI via a pre-built DLC (could be either CPU, GPU or both)
    - [x] TEI via a pre-built DLC (could be either CPU, GPU or both) from a GCS Bucket
  - GKE
    - [x] TGI via a pre-built DLC with a custom Kubernetes configuration for GKE Autopilot mode (on GPU) from the Hugging Face Hub #41 
    - [x] TGI via a pre-built DLC with a custom Kubernetes configuration for GKE Autopilot mode (on GPU) from a GCS Bucket #42 
    - [x] TEI via a pre-built DLC with a custom Kubernetes configuration for GKE Autopilot mode (could be either CPU, GPU or both) #43
    - [x] TEI via a pre-built DLC with a custom Kubernetes configuration for GKE Autopilot mode (could be either CPU, GPU or both) from a GCS Bucket #42

> [!NOTE]
> This issue assumes that the DLCs are already created and can be used as containers for the examples described above.
